sudo: required
services:
    - docker

before_install:
    - docker build -t omers1414/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true omers1414/react-test npm test

after_success:
    - docker build -t omers1414/multi-client ./client
    - docker build -t omers1414/multi-nginx ./nginx
    - docker build -t omers1414/multi-server ./server
    - docker build -t omers1414/multi-worker ./worker
    # log in to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push images to docker hub
    - docker push omers1414/multi-client
    - docker push omers1414/multi-nginx
    - docker push omers1414/multi-server
    - docker push omers1414/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: mult-docker
    env: MultDocker-env
    bucket_name: elasticbeanstalk-us-east-1-790662091625
    bucket_path: mult-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY